# Generated by Django 3.1.3 on 2021-02-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_feed_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='user',
        ),
    ]
