# Generated by Django 3.1.3 on 2021-02-03 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_remove_feed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
