# Generated by Django 3.1.3 on 2021-02-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210203_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_link',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
